app/Http/routes.php
<?php


//Socialite Integration
Route::get('auth/login/{provider}', ['as' => 'auth.provider', 'uses' => 'Auth\AuthController@loginThirdParty']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['Administrator'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'admin'], 
    {

        #Services
        Route::get('service/data', 'ServiceController@data');
        Route::resource('service', 'ServiceController');
        Route::get('service/1/edit', 'ServiceController');

        #Service Activation
        Route::get('service/activate/{id}', 'ServiceController@activate');
        Route::get('service/deactivate', 'ServiceController@deactivate');

        #Categories
        Route::get('category/data', 'CategoryController@data');
        Route::resource('category', 'CategoryController');

        #Features
        Route::get('feature/data', 'FeatureController@data');
        Route::resource('feature', 'FeatureController');

        #Prices
        Route::get('price/data', 'PriceController@data');
        Route::resource('price', 'PriceController');

        #Statuses
        Route::get('status/data', 'StatusController@data');
        Route::resource('status', 'StatusController');

        #Suppliers
        Route::get('supplier/data', 'SupplierController@data');
        Route::resource('supplier', 'SupplierController');
        Route::get('supplier/check', 'SupplierController@check');

        #Orders
        Route::get('order', 'OrderController@index');
        Route::get('order/data', 'OrderController@data');
        Route::get('order/edit', 'OrderController@edit');
    });
});

Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['User'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'client'], function ()
    {
        Route::get('order/create', 'OrderController@create');

    });
});


Route::get('/', 'FrontendController@index');

Route::get('dashboard', 'DashboardController@index');



Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model {

	protected $table = 'categories';
	public $timestamps = true;
	protected $fillable = array('title');
	protected $visible = array('id','title');

	public function services()
	{
		return $this->hasMany('Service');
	}

}

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model {

	protected $table = 'services';
	public $timestamps = false;
	protected $fillable = array('title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier', 'user_id');
	protected $visible = array('id','title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier');
	protected $dates = ['delivery_time'];

	// public function features()
	// {
	// 	return $this->hasMany('Feature', 'id');
	// }

	public function supplier()
	{
		return $this->hasOne('Supplier', 'id');
	}

	public function category()
	{
		return $this->belongsTo('Category', 'id');
	}

	public function price()
	{
		return $this->belongsTo('App\Price');
	}

	public function scopePublished($query){

		$query->where('delivery_time', '<=', Carbon::now()->toDateTimeString());
	}

	public function setPublishedAttribute($date){

		$this->attributes['delivery_time'] = Carbon::parse($date);
	}


	public function user(){

		return $this->belongsTo('App\User');
	}


	public function features(){

		return $this->belongsToMany('App\Feature')->withTimestamps();
	}

	//Get the list of the features associated with given service. 
	//Mostly used on the edits

	//Returns an array
	public function getFeatureListAttribute(){

		return $this->features->lists('id');
	}

	public function getCategoryListAttribute(){

		return $this->features->lists('id');
	}

}

app/Http/Controllers/CategoryController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CategoryRequest;
use App\Http\Controllers\Controller;
use App\Category;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\HttpResponse;

class CategoryController extends Controller {


  public function index()
  {
    return view('backend.services.categories.index');
  }


  public function create()
  {
      return view('backend.services.categories.add');
  }


  public function store(CategoryRequest $request)
  {
      Category::create($request->all());
      return redirect('admin/category');
  }


  public function show($id)
  {
    
  }


  public function edit($id)
  {
      $category = Category::findOrFail($id);
      return view('backend.services.categories.edit' ,compact('category'));
  }


  public function update($id, CategoryRequest $request)
  {
      $category = Category::findOrFail($id);
      $category->update($request->all());
      return redirect('admin/category');
  }



  public function destroy($id)
  {
    
  }
  public function data()
    {
         $categories = Category::select(['id','title']);
      
    return Datatables::of($categories)
        
        ->addColumn('action','
             <div class="btn-group">
                <a href="{{{ URL::to(\'admin/category/\' . $id . \'/edit\' ) }}}" class="btn btn-primary btn-xs iframe" ><i class="fa fa-pencil"></i> Edit</a>
                <a href="{{{ URL::to(\'admin/category/\' . $id . \'/delete\' ) }}}" class="btn btn-xs btn-danger iframe"><i class="fa fa-trash-o"></i> Delete</a>
            </div>
            ')
        
        ->make(true);
    }
}

?>

app/Http/Controllers/ServiceController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\ServiceRequest;
use App\Http\Controllers\Controller;
use App\Service;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\HttpResponse;
use Illuminate\Support\Facades\Auth;

use App\Feature;
use Input;

use Carbon\Carbon;

class ServiceController extends Controller {


  public function index()
  {

    $services = \DB::table('services')->get();    
    $price = \DB::table('prices')->where('id',1)->pluck('title');

    return view('backend.services.index')
    ->with('services', $services)
    ->with('price', $price);
  }


  public function create()
  {

      // $uri = Request::url("http://localhost:9900/admin/service/create");
      // $uri = Request::is('service/create');
      // dd($uri);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = null;
      $selectedSupplierKey = null;
      $selectedPriceKey = null;
      // $company_lists = RecordCompany::lists('company_name', 'id');


      return view('backend.services.add')
          ->with('categories', $categories)
          ->with('features', $features)
          ->with('prices', $prices)
          ->with('suppliers', $suppliers)
          ->with('selectedSupplierKey', $selectedSupplierKey)
          ->with('selectedCategoryKey', $selectedCategoryKey)
          ->with('selectedPriceKey', $selectedPriceKey);
  }


  public function store(ServiceRequest $request)
  {          

      $service = Auth::user()->services()->create($request->all());      

      $service->features()->attach($request->input('feature_list'));
 
      return redirect('admin/service');
  }

  public function activate($id){

      // $service = Service::findOrFail($id);
      dd('service');

      // return redirect('admin/service');
  }

  public function show($id)
  {
      $service = Service::findOrFail($id);

      return view('backend.services.show', compact('service'));
  }


  public function edit($id)
  {
      $service = Service::findOrFail($id);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = \DB::table('services')->where('id', $id)->pluck('category');
      $selectedSupplierKey = \DB::table('services')->where('id', $id)->pluck('supplier');
      $selectedPriceKey = \DB::table('services')->where('id', $id)->pluck('price');

      // dd($categories);
      return view('backend.services.edit')
        ->with('service', $service)
        ->with('categories', $categories)
        ->with('suppliers', $suppliers)
        ->with('features', $features)
        ->with('prices', $prices)
        ->with('selectedCategoryKey', $selectedCategoryKey)
        ->with('selectedPriceKey', $selectedPriceKey)
        ->with('selectedSupplierKey', $selectedSupplierKey);
  }


  public function update($id, ServiceRequest $request)
  {
      // dd($request->all());

      $service = Service::findOrFail($id);
      $service->update($request->all());

      $service->features()->sync($request->input('feature_list'));

      return redirect('admin/service');
  }

  

  public function destroy($id)
  {
    
  }

  public function data()
    {
         $services = Service::select(['id','category','title','price', 'description']);

    return Datatables::of($services)
        
        ->addColumn('action',  '
             <div class="btn-group">
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/edit\' ) }}}" class="btn btn-primary btn-xs iframe" ><i class="fa fa-pencil"></i> Edit</a>
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/delete\' ) }}}" class="btn btn-xs btn-danger iframe"><i class="fa fa-trash-o"></i> Delete</a>
            </div>
            ')
        
        ->make(true);
    }

  public function see(){

    var_dump('Sen');
  }
}

resources/views/backend/services/categories/add.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Features Management | Add')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/category')}}">Categories Management</a></li>
            <li class="active">Add New Category</li>
        </ol>
        <h1 class="page-header">Add Service Category <small>Add New Category</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Category Details</h4>
            </div>
            <div class="panel-body">

    @include('../../errors/list')

    {!! Form::open(['action' => 'CategoryController@store']) !!}

    @include('backend.services.categories.form', ['submitButtonText' => 'Add Category'])

    {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/backend/services/categories/edit.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Features Management | Edit')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/category')}}">Categories Management</a></li>
            <li class="active">Edit: {!! $category->title !!}</li>
        </ol>
        <h1 class="page-header">Edit Category <small>Make Modifications to your Categories</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Edit: {!! $category->title !!}</h4>
            </div>
            <div class="panel-body">

    @include('../../errors/list')

    {!! Form::model($category, ['method' => 'PATCH', 'action' => ['CategoryController@update', $category->id]]) !!}

    @include('backend.services.categories.form ', ['submitButtonText' => 'Update Category'])

    {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/backend/services/categories/form.blade.php
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, array('required','class'=>'form-control', 'placeholder'=>'Title'))!!}
</div>

<div class="form-group">
    {!! Form::submit($submitButtonText, ['class' => 'btn btn-primary']) !!}
</div>

resources/views/backend/services/categories/index.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Categories Management')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li class="active">Categories Management</li>
        </ol>
        <h1 class="page-header">Manage Categories <small>Add/Remove/Edit Categories</small></h1>

        <div class="pull-right" style="margin-bottom:10px">
            <a href="{{route('admin.category.create')}}" class="btn btn-success btn"><i class="fa fa-plus"></i> New Category</a>
        </div>
        <div class="clearfix"></div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Categories List</h4>
            </div>
            <div class="panel-body">
		<table id="category-table" class="table table-hover table-bordered">
			<thead>
				<tr>
					<th>ID</th>
					<th>Category Name</th>
                    <th>Actions</th>
				</tr>
			</thead>
	</table>
	</div>
             </div>
	       </div>

@endsection

@push('scripts')
<script>
$('#category-table').DataTable({
        processing: true,
		serverSide: true,
		ajax: "{{ URL::to('admin/category/data/') }}",

        columns: [
			{data: 'id', name: 'id'},
			{data: 'title', name: 'title'},
			{data: 'action', name: 'action', orderable: false, searchable: false}
		]
                                 });


        

</script>
@endpush