app/Http/routes.php
<?php


//Socialite Integration
Route::get('auth/login/{provider}', ['as' => 'auth.provider', 'uses' => 'Auth\AuthController@loginThirdParty']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['Administrator'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'admin'], 
    {

        #Services
        Route::get('service/data', 'ServiceController@data');
        Route::resource('service', 'ServiceController');
        Route::get('service/1/edit', 'ServiceController');

        #Service Activation
        Route::get('service/activate/{id}', 'ServiceController@activate');
        Route::get('service/deactivate', 'ServiceController@deactivate');

        #Categories
        Route::get('category/data', 'CategoryController@data');
        Route::resource('category', 'CategoryController');

        #Features
        Route::get('feature/data', 'FeatureController@data');
        Route::resource('feature', 'FeatureController');

        #Prices
        Route::get('price/data', 'PriceController@data');
        Route::resource('price', 'PriceController');

        #Statuses
        Route::get('status/data', 'StatusController@data');
        Route::resource('status', 'StatusController');

        #Suppliers
        Route::get('supplier/data', 'SupplierController@data');
        Route::resource('supplier', 'SupplierController');
        Route::get('supplier/check', 'SupplierController@check');

        #Orders
        Route::get('order', 'OrderController@index');
        Route::get('order/data', 'OrderController@data');
        Route::get('order/edit', 'OrderController@edit');
    });
});

Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['User'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'client'], function ()
    {
        Route::get('order/create', 'OrderController@create');

    });
});


Route::get('/', 'FrontendController@index');

Route::get('dashboard', 'DashboardController@index');



Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

app/Feature.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feature extends Model {

	protected $table = 'features';
	// public $timestamps = true;
	protected $fillable = array('description');
	protected $visible = array('id','description');


	public function services(){

		return $this->belongsTomany('App\Service');
	}
}

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model {

	protected $table = 'services';
	public $timestamps = false;
	protected $fillable = array('title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier', 'user_id');
	protected $visible = array('id','title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier');
	protected $dates = ['delivery_time'];

	// public function features()
	// {
	// 	return $this->hasMany('Feature', 'id');
	// }

	public function supplier()
	{
		return $this->hasOne('Supplier', 'id');
	}

	public function category()
	{
		return $this->belongsTo('Category', 'id');
	}

	public function price()
	{
		return $this->belongsTo('App\Price');
	}

	public function scopePublished($query){

		$query->where('delivery_time', '<=', Carbon::now()->toDateTimeString());
	}

	public function setPublishedAttribute($date){

		$this->attributes['delivery_time'] = Carbon::parse($date);
	}


	public function user(){

		return $this->belongsTo('App\User');
	}


	public function features(){

		return $this->belongsToMany('App\Feature')->withTimestamps();
	}

	//Get the list of the features associated with given service. 
	//Mostly used on the edits

	//Returns an array
	public function getFeatureListAttribute(){

		return $this->features->lists('id');
	}

	public function getCategoryListAttribute(){

		return $this->features->lists('id');
	}

}

app/Http/Controllers/FeatureController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\FeatureRequest;
use App\Http\Controllers\Controller;
use App\Feature;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\HttpResponse;

class FeatureController extends Controller {


  public function index()
  {
    return view('backend.services.features.index');
  }


  public function create()
  {
      return view('backend.services.features.add');
  }


  public function store(FeatureRequest $request)
  {
      Feature::create($request->all());
      // dd($request->all());
      return redirect('admin/feature');
  }


  public function show($id)
  {
    
  }


  public function edit($id)
  {
      $feature = Feature::findOrFail($id);
      return view('backend.services.features.edit' ,compact('feature'));
  }


  public function update($id, FeatureRequest $request)
   {
        $feature = Feature::findOrFail($id);
        $feature->update($request->all());
        return redirect('admin/feature');
   }


  public function destroy($id)
  {
    $feature = Feature::findOrFail($id);
    $feature->delete();
 
    return Redirect::route('features.index')->with('message', 'features deleted.');
  }


  public function data()
    {
         $features = Feature::select(['id','description']);
      
    return Datatables::of($features)
        
        ->addColumn('action', '
             <div class="btn-group">
                <a href="{{{ URL::to(\'admin/feature/\' . $id . \'/edit\' ) }}}" class="btn btn-primary btn-xs iframe" ><i class="fa fa-pencil"></i> Edit</a>
                <a href="{{{ URL::to(\'admin/feature/\' . $id ) }}}" class="btn btn-xs btn-danger iframe"><i class="fa fa-trash-o"></i> Delete</a>
            </div>
            ')
        
        ->make(true);
    }
}

?>

app/Http/Controllers/ServiceController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\ServiceRequest;
use App\Http\Controllers\Controller;
use App\Service;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\HttpResponse;
use Illuminate\Support\Facades\Auth;

use App\Feature;
use Input;

use Carbon\Carbon;

class ServiceController extends Controller {


  public function index()
  {

    $services = \DB::table('services')->get();    
    $price = \DB::table('prices')->where('id',1)->pluck('title');

    return view('backend.services.index')
    ->with('services', $services)
    ->with('price', $price);
  }


  public function create()
  {

      // $uri = Request::url("http://localhost:9900/admin/service/create");
      // $uri = Request::is('service/create');
      // dd($uri);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = null;
      $selectedSupplierKey = null;
      $selectedPriceKey = null;
      // $company_lists = RecordCompany::lists('company_name', 'id');


      return view('backend.services.add')
          ->with('categories', $categories)
          ->with('features', $features)
          ->with('prices', $prices)
          ->with('suppliers', $suppliers)
          ->with('selectedSupplierKey', $selectedSupplierKey)
          ->with('selectedCategoryKey', $selectedCategoryKey)
          ->with('selectedPriceKey', $selectedPriceKey);
  }


  public function store(ServiceRequest $request)
  {          

      $service = Auth::user()->services()->create($request->all());      

      $service->features()->attach($request->input('feature_list'));
 
      return redirect('admin/service');
  }

  public function activate($id){

      // $service = Service::findOrFail($id);
      dd('service');

      // return redirect('admin/service');
  }

  public function show($id)
  {
      $service = Service::findOrFail($id);

      return view('backend.services.show', compact('service'));
  }


  public function edit($id)
  {
      $service = Service::findOrFail($id);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = \DB::table('services')->where('id', $id)->pluck('category');
      $selectedSupplierKey = \DB::table('services')->where('id', $id)->pluck('supplier');
      $selectedPriceKey = \DB::table('services')->where('id', $id)->pluck('price');

      // dd($categories);
      return view('backend.services.edit')
        ->with('service', $service)
        ->with('categories', $categories)
        ->with('suppliers', $suppliers)
        ->with('features', $features)
        ->with('prices', $prices)
        ->with('selectedCategoryKey', $selectedCategoryKey)
        ->with('selectedPriceKey', $selectedPriceKey)
        ->with('selectedSupplierKey', $selectedSupplierKey);
  }


  public function update($id, ServiceRequest $request)
  {
      // dd($request->all());

      $service = Service::findOrFail($id);
      $service->update($request->all());

      $service->features()->sync($request->input('feature_list'));

      return redirect('admin/service');
  }

  

  public function destroy($id)
  {
    
  }

  public function data()
    {
         $services = Service::select(['id','category','title','price', 'description']);

    return Datatables::of($services)
        
        ->addColumn('action',  '
             <div class="btn-group">
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/edit\' ) }}}" class="btn btn-primary btn-xs iframe" ><i class="fa fa-pencil"></i> Edit</a>
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/delete\' ) }}}" class="btn btn-xs btn-danger iframe"><i class="fa fa-trash-o"></i> Delete</a>
            </div>
            ')
        
        ->make(true);
    }

  public function see(){

    var_dump('Sen');
  }
}

resources/views/backend/services/features/add.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Features Management | Add')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/feature')}}">Features Management</a></li>
            <li class="active">Add New Feature</li>
        </ol>
        <h1 class="page-header">Add Service Feature <small>Add New Feature</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Feature Details</h4>
            </div>
            <div class="panel-body">

    @include('../../errors/list')

    {!! Form::open(['action' => 'FeatureController@store']) !!}

    @include('backend.services.features.form', ['submitButtonText' => 'Add Feature'])

    {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/backend/services/features/edit.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Features Management | Edit')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/feature')}}">Features Management</a></li>
            <li class="active">Edit: {!! $feature->title !!}</li>
        </ol>
        <h1 class="page-header">Edit Feature <small>Make Modifications to your Feature</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Edit: {!! $feature->title !!}</h4>
            </div>
            <div class="panel-body">

    @include('../../errors/list')

    {!! Form::model($feature, ['method' => 'PATCH', 'action' => ['FeatureController@update', $feature->id]]) !!}

    @include('backend.services.features.form ', ['submitButtonText' => 'Update Feature'])

    {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/backend/services/features/form.blade.php
<div class="form-group">
    {!! Form::label('description', 'Title:') !!}
    {!! Form::text('description', null, array('required','class'=>'form-control', 'placeholder'=>'Enter description for Feature'))!!}
</div>

<div class="form-group">
    {!! Form::submit($submitButtonText, ['class' => 'btn btn-primary']) !!}
</div>

resources/views/backend/services/features/index.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Features Management')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li class="active">Features Management</li>
        </ol>
        <h1 class="page-header">Manage Features <small>Add/Remove/Edit Features</small></h1>

        <div class="pull-right" style="margin-bottom:10px">
            <a href="{{route('admin.feature.create')}}" class="btn btn-success btn"><i class="fa fa-plus"></i> New Feature</a>
        </div>
        <div class="clearfix"></div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Features List</h4>
            </div>
            <div class="panel-body">
		<table id="feature-table" class="table table-hover table-bordered">
			<thead>
				<tr>
					<th>ID</th>
					<th>Title</th>
                    <th>Actions</th>
				</tr>
			</thead>
	</table>
	</div>
</div>
                </div>

@endsection

@push('scripts')
<script>
$(function() {
	$('#feature-table').DataTable({
		processing: true,
		serverSide: true,
		ajax: "{{ URL::to('admin/feature/data/') }}",
        columns: [
			{data: 'id', name: 'id'},
			{data: 'description', name: 'description'},
			{data: 'action', name: 'action', orderable: false, searchable: false}
		]        
        });
});
</script>
@endpush