app/Http/routes.php
<?php


//Socialite Integration
Route::get('auth/login/{provider}', ['as' => 'auth.provider', 'uses' => 'Auth\AuthController@loginThirdParty']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['Administrator'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'admin'], 
    {

        #Services
        Route::get('service/data', 'ServiceController@data');
        Route::resource('service', 'ServiceController');
        Route::get('service/1/edit', 'ServiceController');

        #Service Activation
        Route::get('service/activate/{id}', 'ServiceController@activate');
        Route::get('service/deactivate', 'ServiceController@deactivate');

        #Categories
        Route::get('category/data', 'CategoryController@data');
        Route::resource('category', 'CategoryController');

        #Features
        Route::get('feature/data', 'FeatureController@data');
        Route::resource('feature', 'FeatureController');

        #Prices
        Route::get('price/data', 'PriceController@data');
        Route::resource('price', 'PriceController');

        #Statuses
        Route::get('status/data', 'StatusController@data');
        Route::resource('status', 'StatusController');

        #Suppliers
        Route::get('supplier/data', 'SupplierController@data');
        Route::resource('supplier', 'SupplierController');
        Route::get('supplier/check', 'SupplierController@check');

        #Orders
        Route::get('order', 'OrderController@index');
        Route::get('order/data', 'OrderController@data');
        Route::get('order/edit', 'OrderController@edit');
    });
});

Route::group([
    'middleware' => 'vault.routeNeedsRole',
    'role' => ['User'],
    'redirect' => '/',
    'with' => ['error', 'You do not have access to this section.']
], function()
{
    Route::group(['prefix' => 'client'], function ()
    {
        Route::get('order/create', 'OrderController@create');

    });
});


Route::get('/', 'FrontendController@index');

Route::get('dashboard', 'DashboardController@index');



Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model {

	protected $table = 'services';
	public $timestamps = false;
	protected $fillable = array('title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier', 'user_id');
	protected $visible = array('id','title', 'category', 'description', 'image', 'delivery_time', 'price', 'supplier');
	protected $dates = ['delivery_time'];

	// public function features()
	// {
	// 	return $this->hasMany('Feature', 'id');
	// }

	public function supplier()
	{
		return $this->hasOne('Supplier', 'id');
	}

	public function category()
	{
		return $this->belongsTo('Category', 'id');
	}

	public function price()
	{
		return $this->belongsTo('App\Price');
	}

	public function scopePublished($query){

		$query->where('delivery_time', '<=', Carbon::now()->toDateTimeString());
	}

	public function setPublishedAttribute($date){

		$this->attributes['delivery_time'] = Carbon::parse($date);
	}


	public function user(){

		return $this->belongsTo('App\User');
	}


	public function features(){

		return $this->belongsToMany('App\Feature')->withTimestamps();
	}

	//Get the list of the features associated with given service. 
	//Mostly used on the edits

	//Returns an array
	public function getFeatureListAttribute(){

		return $this->features->lists('id');
	}

	public function getCategoryListAttribute(){

		return $this->features->lists('id');
	}

}

app/Http/Controllers/ServiceController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\ServiceRequest;
use App\Http\Controllers\Controller;
use App\Service;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\HttpResponse;
use Illuminate\Support\Facades\Auth;

use App\Feature;
use Input;

use Carbon\Carbon;

class ServiceController extends Controller {


  public function index()
  {

    $services = \DB::table('services')->get();    
    $price = \DB::table('prices')->where('id',1)->pluck('title');

    return view('backend.services.index')
    ->with('services', $services)
    ->with('price', $price);
  }


  public function create()
  {

      // $uri = Request::url("http://localhost:9900/admin/service/create");
      // $uri = Request::is('service/create');
      // dd($uri);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = null;
      $selectedSupplierKey = null;
      $selectedPriceKey = null;
      // $company_lists = RecordCompany::lists('company_name', 'id');


      return view('backend.services.add')
          ->with('categories', $categories)
          ->with('features', $features)
          ->with('prices', $prices)
          ->with('suppliers', $suppliers)
          ->with('selectedSupplierKey', $selectedSupplierKey)
          ->with('selectedCategoryKey', $selectedCategoryKey)
          ->with('selectedPriceKey', $selectedPriceKey);
  }


  public function store(ServiceRequest $request)
  {          

      $service = Auth::user()->services()->create($request->all());      

      $service->features()->attach($request->input('feature_list'));
 
      return redirect('admin/service');
  }

  public function activate($id){

      // $service = Service::findOrFail($id);
      dd('service');

      // return redirect('admin/service');
  }

  public function show($id)
  {
      $service = Service::findOrFail($id);

      return view('backend.services.show', compact('service'));
  }


  public function edit($id)
  {
      $service = Service::findOrFail($id);

      $categories = \DB::table('categories')->lists('title', 'id');
      $features = \DB::table('features')->lists('description', 'id');
      $suppliers = \DB::table('suppliers')->lists('title', 'id');
      $prices = \DB::table('prices')->lists('title', 'id');
      $selectedCategoryKey = \DB::table('services')->where('id', $id)->pluck('category');
      $selectedSupplierKey = \DB::table('services')->where('id', $id)->pluck('supplier');
      $selectedPriceKey = \DB::table('services')->where('id', $id)->pluck('price');

      // dd($categories);
      return view('backend.services.edit')
        ->with('service', $service)
        ->with('categories', $categories)
        ->with('suppliers', $suppliers)
        ->with('features', $features)
        ->with('prices', $prices)
        ->with('selectedCategoryKey', $selectedCategoryKey)
        ->with('selectedPriceKey', $selectedPriceKey)
        ->with('selectedSupplierKey', $selectedSupplierKey);
  }


  public function update($id, ServiceRequest $request)
  {
      // dd($request->all());

      $service = Service::findOrFail($id);
      $service->update($request->all());

      $service->features()->sync($request->input('feature_list'));

      return redirect('admin/service');
  }

  

  public function destroy($id)
  {
    
  }

  public function data()
    {
         $services = Service::select(['id','category','title','price', 'description']);

    return Datatables::of($services)
        
        ->addColumn('action',  '
             <div class="btn-group">
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/edit\' ) }}}" class="btn btn-primary btn-xs iframe" ><i class="fa fa-pencil"></i> Edit</a>
                <a href="{{{ URL::to(\'admin/service/\' . $id . \'/delete\' ) }}}" class="btn btn-xs btn-danger iframe"><i class="fa fa-trash-o"></i> Delete</a>
            </div>
            ')
        
        ->make(true);
    }

  public function see(){

    var_dump('Sen');
  }
}

resources/views/backend/services/add.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Services Management | Add')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/service')}}">Services Management</a></li>
            <li class="active">Add New Service</li>
        </ol>
        <h1 class="page-header">Add New Service <small>Add New Service</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Service Details</h4>
            </div>
            <div class="panel-body">

                @include('../../errors/list')

                {!! Form::open(['action' => 'ServiceController@store']) !!}

                @include('backend.services.form', ['submitButtonText' => 'Add Service'])

                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/backend/services/edit.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Services Management | Edit')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li><a href="{{url('admin/service')}}">Services Management</a></li>
            <li class="active">Edit: {!! $service->title !!}</li>
        </ol>
        <h1 class="page-header">Edit Service <small>Make Modifications to your Service</small></h1>


        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Edit: {!! $service->title !!}</h4>
            </div>
            <div class="panel-body">

                @include('../../errors/list')

                {!! Form::model($service, ['method' => 'PATCH', 'action' => ['ServiceController@update', $service->id]]) !!}

                @include('backend.services.form', ['submitButtonText' => 'Update Service'])

                {!! Form::close() !!}
            </div>
        </div>
    </div>

@stop

resources/views/backend/services/form.blade.php
<div class="box box-primary">
    <div class="box-body">

       <span class="pull-right">
            {!! Form::select('active', array('on' => 'active', 'off' => 'Not active',), 
                Input::old('active', 1), 
                array('class'=>'btn btn-sm btn-primary', 'id'=>'active')) !!}
        </span>

        <div class="form-group">
            {!! Form::label('title', 'Title:') !!}
            {!! Form::text('title', null, array('class'=>'form-control', 'placeholder'=>'Title')) !!}
        </div>
        
        <div class="form-group">
            {!! Form::label('Category:') !!}
            {!! Form::select('category', (['0' => 'Select a Category'] + $categories), $selectedCategoryKey, ['class' => 'form-control']) !!}
        </div>
       

        <div class="form-group">
            {!! Form::label('description', 'Description:') !!}
            {!! Form::textarea('description', null, array('required','class'=>'ckeditor'))!!}
        </div>

        <div class="form-group">
            {!! Form::label('image', 'Image:') !!}
            {!! Form::file('image') !!}
        </div>

        <div class="form-group">
            {!! Form::label('delivery_time', 'Delivery Time:') !!}
            {!! Form::input('date','delivery_time', date('Y-m-d'), array('class'=>'form-control', 'placeholder'=>'Enter Delivery Time'))!!}
        </div>


        <div class="form-group">            
            {!! Form::label('feature_list', 'Features:') !!} <br>
            {!! Form::select('feature_list[]', $features, null, ['class'=>'form-control', 'multiple']) !!}
            <br />
        </div>

        <div class="form-group">
            {!! Form::label('price', 'Price Group:') !!}
            {!! Form::select('price', (['0' => 'Select a Price Group'] + $prices), $selectedPriceKey, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('supplier', 'Supplier API:') !!}
            {!! Form::select('supplier', (['0' => 'Select a Supplier'] + $suppliers), $selectedSupplierKey, ['class' => 'form-control']) !!}
        </div>

    
        <div class="form-group">
            {!! Form::submit($submitButtonText, ['class' => 'btn btn-primary']) !!}
        </div>
    </div>
</div>
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>

resources/views/backend/services/index.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Services Management')

@section('content')

    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li><a href="{{url('/dashboard')}}">Dashboard</a></li>
            <li class="active">Services Management</li>
        </ol>
        <h1 class="page-header">Manage Services <small>Add/Remove/Edit Services</small></h1>

        <div class="pull-right" style="margin-bottom:10px">
            <a href="{{route('admin.service.create')}}" class="btn btn-success btn"><i class="fa fa-plus"></i> New Service</a>  
            <a href="#" class="btn btn-primary btn" onclick="activate()">Activate Selected</a> 
            <a href="#" class="btn btn-danger btn" onclick="GetCellValues()">Deactivate Selected</a>

            <input type="button" onclick="activate()" value="Click">
        </div>
        <div class="clearfix"></div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>

                </div>
                <h4 class="panel-title">Services List</h4>
            </div>
            <div class="panel-body">
        		<table id="service-table" class="table table-striped table-hover table-bordered" data-click-to-select="true">
            			<thead>
            				<tr>
            					<th>ID</th>
                                <th>Service</th>
                                <th>Description</th>
            					<th>Actions</th>
            				</tr>
            			</thead>
            	</table>

                <!-- <table data-url="data1.json" data-height="299" data-click-to-select="true">
                    <thead>
                        <tr>
                            <th data-field="state" data-checkbox="true"></th>
                            <th data-field="id" data-align="right">Item ID</th>
                            <th data-field="name" data-align="center">Item Name</th>
                            <th data-field="price" data-align="">Item Price</th>
                        </tr>
                    </thead>
                </table> -->

        	</div>
        </div>
    </div>
@endsection

@push('scripts')
<script>
$(function() {
    var category = 'category';
    var price = price;
    $('#service-table').DataTable({
		processing: true,
		serverSide: true,
		ajax: "{{ URL::to('admin/service/data/') }}",
        dom: 'T<"clear">lfrtip',
        tableTools: { "sRowSelect": "os",
                     "aButtons": [ "select_all", "select_none", "print",
                         { "sExtends": "collection", "sButtonText": "Save as", "aButtons": [ "csv", "xls", "pdf" ] } ] },
        columns: [
			{data: 'id', name: 'id'},
			{data: 'title', name: 'title'},
            {data: 'description', name: 'description' },
			// {data: 'price, name: 'price'},
			{data: 'action', name: 'action', orderable: false, searchable: false}
		]
    });

    console.log('id');
});

function activate(){
    console.log('activated');
}

function GetCellValues() {
    var table = $('#service-table').DataTable( {
    columns: [
        { name: 'id' },
        { title: 'description'}
        ]
    } );
     
    // Get salary column data
    var data = table.column( 'id:name' ).data();
    console.log(data[0]);

}


</script>
@endpush

resources/views/backend/services/show.blade.php
@extends ('../../layouts.admin')

@section ('title', 'Services Management Show')

@section('content')
	<div id="content" class="content">
		<!-- begin breadcrumb -->
		<ol class="breadcrumb pull-right">
			<li><a href="javascript:;">Home</a></li>
			<li><a href="javascript:;">Page Options</a></li>
			<li class="active">Service Management Show</li>
		</ol>
		<!-- end breadcrumb -->
		<!-- begin page-header -->
		<h1 class="page-header">Service Management Show</h1>
		<!-- end page-header -->
		
		<div class="panel panel-inverse">
		    <div class="panel-heading">
		        <div class="panel-heading-btn">
		            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand" data-original-title="" title=""><i class="fa fa-expand"></i></a>
		            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload" data-original-title="" title=""><i class="fa fa-repeat"></i></a>
		            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse" data-original-title="" title=""><i class="fa fa-minus"></i></a>
		            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
		        </div>
		        <h4 class="panel-title">{!! $service->title !!}</h4>
		    </div>
		    <div class="panel-body">
		        <div class="note note-success">
					<h4>Image: <span>Image heres</span></h4>
					<h4>Category: <span>{!! $service->category !!}</span></h4>
					<h4>Description: <span>{!! $service->description !!}</span></h4>
					<h4>Features: <span>{!! $service->features !!}</span></h4>
					<h4>Delivery Time: <span>{!! $service->delivery_time !!}</span></h4>
					<h4>Price: <span>{!! $service->price !!}</span></h4>
					<h4>Supplier: <span>{!! $service->supplier !!}</span></h4>
				</div>
		    </div>
		</div>
	</div>

@endsection